### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by severinolorillajr** [code-dot-org/code-dot-org#20419]
Hi, I don't know where to ask these questions.

I am currently working on your CrowdIn project, and have translated about 25% of the entire project.
Was just wondering, if you also need Filipino / Tagalog translations here or in any of your Github directory?
I can also translate documentations and guides if needed, aside from the tutorial.

Thanks.

**Comment by safruddin88** [comment]
what is open source?

**Comment by tanyaparker** [comment]
Hi @severinolorillajr! Thank you for helping us with translations. You won't need to translate anything in our Github directory. Everything is either in CrowdIn or on Asana (for video subtitles). [Click here](https://code.org/translate/videos) for more info on translating our video subtitles.

Hi @safruddin88! Open source means that the code is visible to the public and available to be edited by people outside of the organization. You can read more about [open source software here](https://opensource.com/resources/what-open-source).

**Comment by severinolorillajr** [comment]
Hi @tanyaparker 
Can someone check your crowdin project? or maybe the my ticket on code.org website?
I just have a few minor requests before I can proceed with the translations.
I am very much eager to contribute and finish the project.

However I will be needing a proofreader role.
I have sent a very detailed on my messaged there.
Hope someone can check.

Thanks.

**Comment by tanyaparker** [comment]
Hi @severinolorillajr,

Have you tried sending us an email at translations@code.org? Can you include links to your reports on Crowdin as well? Our International Program Manager will get back to you as soon as she can.

Best,
Tanya

**Comment by severinolorillajr** [comment]
Thanks for the feedback @tanyaparker .
I already sent an email to translations@code.org regarding my request.
And have included some links to my profile, the project, etc.
Thanks a lot.
Cheers!

**Comment by severinolorillajr** [comment]
Hi @tanyaparker, do you have some news?
I already sent an email, and it appears that they have already read it,
But I haven't got any replies.
