### ISSUE TITLE
I would like to translate code.org

### ISSUE THREAD

**Issue by rooneey** [code-dot-org/code-dot-org#20446]
Hi....I am a native speaker of Indonesian Language. Can I contribute to translate some files?

**Comment by tanyaparker** [comment]
Hi @rooneey, you absolutely can! We use CrowdIn for all of our curriculum translations. Please visit code.org/translate for more information, or you can get started by joining the [Indonesian Crowdin project here](https://crowdin.com/project/codeorg/id). We do not do any translations through GitHub.

If you have any further questions, please email translations@code.org.

Best,
Tanya

**Comment by rooneey** [comment]
I think i can help through github because utopian-io obligates us to use
github....

Pada tanggal 7 Feb 2018 01:53, "Tanya Parker" <notifications@github.com>
menulis:

**Comment by rooneey** [comment]
Hi...I am a native speaker of Indonesian, can I become one of proofreaders here?
It will really helpful for me to translate more here. Please put me on the list of proofreaders
