### ISSUE TITLE
Missing Dash on code.org/research

### ISSUE THREAD

**Issue by asherkach** [code-dot-org/code-dot-org#20445]
Under "Research Partnerships", there is a missing dash for Dr. Briana Morrison between "University of Nebraska at Omaha" and "Subgoal Labels Study in CSP Unit 3".

Presumably this needs to be fixed in the content pipeline rather than directly in GitHub (thus the issue report rather than a PR).

**Comment by tanyaparker** [comment]
Thanks, @asherkach! I've put in the fix.
