### ISSUE TITLE
Improving stats

### ISSUE THREAD

**Issue by Cosaca** [code-dot-org/code-dot-org#21802]
Hello, I was interested in making a contribution related to stats in your platform that are displayed in each section. I was thinking about using a tool called Chartkick to show them, it will be posible to use this? 
I mean by the way the platform is designed.

Thank you.

**Comment by tanyaparker** [comment]
Hi @Cosaca,

Can you give me a little more information about what you're looking to do? What page are you looking at for the stats? By section do you mean a classroom section or a section on the page? If you want to make charts of the stats, which stats are you going to make a graph of, what kind of graph would it be, and what does it look like with Chartkick? Is Chartkick open source and what are the pros and cons of its API?

Best,
Tanya

**Comment by Cosaca** [comment]
First of all, thank for your response.
I was looking for improving the way stats are showed in each section that teachers create, I mean inside this tab (those are examples of students):

<img width="985" alt="captura de pantalla 2018-04-14 a las 11 17 37" src="https://user-images.githubusercontent.com/17838267/38767235-9c5e5902-3fd5-11e8-87c7-2ea9c8683eb6.png">

I thought maybe another representation of that data tables would be nice, just below that table. Because of that I suggested Chartkick (open source by the way), that provide some charts, I guess useful, to show that results, like this (that is an example of their webpage https://www.chartkick.com/):

<img width="986" alt="captura de pantalla 2018-04-14 a las 11 21 37" src="https://user-images.githubusercontent.com/17838267/38767268-068ab082-3fd6-11e8-9feb-fff68a9e4681.png">

But I was wondering if I can get any tip of how to implement this on your repo, because it's a bit too large for me 😅. Sorry for this long message, and thank you again.

**Comment by ngmaster77** [comment]
Hello @tanyaparker Im interested too!

Thanks
