### ISSUE TITLE
setup problem with ruby

### ISSUE THREAD

**Issue by hhmaas** [code-dot-org/code-dot-org#21859]
when i start the setup i got an errormessage after the "sudo apt-get install -y git mysql-server mysql-client libmysqlclient-dev libxslt1-dev libssl-dev zlib1g-dev imagemagick libmagickcore-dev libmagickwand-dev openjdk-9-jre-headless libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev curl pdftk enscript libsqlite3-dev phantomjs build-essential redis-server rbenv ruby-build npm ruby2.5-dev"-command. i got hte following errormessages: 
E: Unable to locate package ruby2.5-dev
E: Couldn't find any package by glob 'ruby2.5-dev'
E: Couldn't find any package by regex 'ruby2.5-dev'
do you have a solution for the problem?
thanks

**Comment by wjordan** [comment]
Hi @hhmaas, we just upgraded Ruby to version 2.5 recently, and it looks like there's an extra step necessary for the Ubuntu installation steps to work correctly that I haven't updated in our setup instructions. Try running the following additional commands:

```
sudo apt-get install -y software-properties-common
sudo apt-add-repository -y ppa:brightbox/ruby-ng
sudo apt-get update
```

After this try running the above `sudo apt-get install` command again. Let me know if this works for you, and I'll update the doc to add this missing step. Sorry for the omission!

**Comment by hhmaas** [comment]
Hi Will,

thanks for the quick response!

It is working now until rbenv install 2.5.0, than i got the message: 
ruby-build: definition not found: 2.5.0
the following version contain '2.5.0' in the name: rbx-2.5.0

ignoring this message, i got as response to the rbenv global 2.5.0 the response: rbenv: version '2.5.0' not installed

is this a follow up of the earlier error and how can i avoid it

Thanks
Hans-Henning

 


)

 

 

 

-----Ursprüngliche Mitteilung----- 
Von: Will Jordan <notifications@github.com>
An: code-dot-org/code-dot-org <code-dot-org@noreply.github.com>
Cc: hhmaas <hhmaas@aol.com>; Mention <mention@noreply.github.com>
Verschickt: Sa, 14. Apr 2018 0:37
Betreff: Re: [code-dot-org/code-dot-org] setup problem with ruby (#21859)



Hi @hhmaas, we just upgraded Ruby to version 2.5 recently, and it looks like there's an extra step necessary for the Ubuntu installation steps to work correctly that I haven't updated in our setup instructions. Try running the following additional commands:
sudo apt-get install -y software-properties-common
sudo apt-add-repository -y ppa:brightbox/ruby-ng
sudo apt-get update

After this try running the above sudo apt-get install command again. Let me know if this works for you, and I'll update the doc to add this missing step. Sorry for the omission!

**Comment by wjordan** [comment]
@hhmaas apologies again, it looks like our Ubuntu setup-instructions document has become a bit incoherent since #16599 and #20879, and probably needs a full rewrite at this point to be able to follow it exactly.

If you have Ruby 2.5 already installed successfully using the steps above (you can check by running `ruby -v`), you can skip the rest of the 'rbenv' steps in the written instructions and proceed from there.

**Comment by hhmaas** [comment]
Hi,

everythink was okay until: bundle install
Than i got the errormessage: your ruby version is 2.3.7, but your gemfile specified 2.5

Do you want to have the install log?

brgds

 

 

 

-----Ursprüngliche Mitteilung----- 
Von: Will Jordan <notifications@github.com>
An: code-dot-org/code-dot-org <code-dot-org@noreply.github.com>
Cc: hhmaas <hhmaas@aol.com>; Mention <mention@noreply.github.com>
Verschickt: So, 15. Apr 2018 2:34
Betreff: Re: [code-dot-org/code-dot-org] setup problem with ruby (#21859)



@hhmaas apologies again, it looks like our Ubuntu setup-instructions document has become a bit incoherent since #16599 and #20879, and probably needs a full rewrite at this point to be able to follow it exactly.
If you have Ruby 2.5 already installed successfully using the steps above (you can check by running ruby -v), you can skip the rest of the 'rbenv' steps in the written instructions and proceed from there.

**Comment by wjordan** [comment]
The error message says that Ruby 2.5.0 is the minimum required version for this project and you haven't installed it correctly. You'll need to figure out how to update/install Ruby in your local environment on your own, I can't help any further with that step.

Refer to documentation [rbenv](https://github.com/rbenv/rbenv), [rvm](https://rvm.io/), or [brightbox ruby](https://www.brightbox.com/blog/2018/02/05/ruby-2-5-ubuntu-packages/), or search on Google for a Ruby-beginner installation guide.
