### ISSUE TITLE
Honeybadger error

### ISSUE THREAD

**Issue by hhmaas** [code-dot-org/code-dot-org#21997]
Hi, 
after the command "rake install:hooks" i get the following errormessage:
rake install:hooks
** [Honeybadger] Initializing Honeybadger Error Tracker for Ruby. Ship it! version=3.3.0 framework=ruby level=1 pid=12878
** [Honeybadger] Development mode is enabled. Data will not be reported until you deploy your app. level=2 pid=12878
ln -s ../../tools/hooks/pre-commit .git/hooks/pre-commit
** [Honeybadger] Unable to send error report: API key is missing. id=7cac4f20-3b23-4f0c-87d4-fad4fb8baf68 level=3 pid=12878
rake aborted!
'ln -s ../../tools/hooks/pre-commit .git/hooks/pre-commit' returned 1
ln: Die symbolische Verknüpfung '.git/hooks/pre-commit' konnte nicht angelegt werden: Keine Berechtigung
Tasks: TOP => install:hooks
(See full trace by running task with --trace)

What does it mean and how can i avoid it

Thanks

**Comment by balderdash** [comment]
The Honeybadger messages are a red herring, the actual problem is:
```
ln: Die symbolische Verknüpfung '.git/hooks/pre-commit' konnte nicht angelegt werden: Keine Berechtigung
```

I don't speak German but it looks like it's not letting you write the file `.git/hooks/pre-commit`. Do you have permission to write to that directory?

**Comment by hhmaas** [comment]
Hi, 
sorry, was my error
