### ISSUE TITLE
code-studio-common.js is about 10M

### ISSUE THREAD

**Issue by hijason1301** [code-dot-org/code-dot-org#23004]
code-studio-common.js is about 10M. essential.js about 1.6 M.
I suppose the version we downloaded has been complied. To big size of one js file. It's very slow to open the the website when we visit it for the first time.
 It must be some history reason. Is there any way of any thoughts to improve it?

**Comment by jeremydstone** [comment]
Thanks. We continue to work on all aspects of site performance. A variety of improvements are on our roadmap.
