### ISSUE TITLE
very diffcult to put a static page

### ISSUE THREAD

**Issue by hijason1301** [code-dot-org/code-dot-org#23005]
for example: http://localhost.code.org:3000/student/elementary. It works in development environment
if we bind to another domain name. for example:  http://localhost.XXX.com:3000/student/elementary, 't ieRouter can't find this page. It's a static page put in pegasus site.v3. 
But there is a complex logic for putting a new domain name. Suggest  to give a simple introduction for how to put static pages. It's a easy start point .

**Comment by hijason1301** [comment]
Considering the development and production mode, it's very hard to start this project. Multi-Domain, two  environment, complicated router. It's difficult to put a simple static page .

**Comment by jeremydstone** [comment]
Thanks for the comment. We are optimized, as you notice, around our product & production scenario and our domain names. We continue to think about ways to make easier starting points and will keep this in mind.
