### ISSUE TITLE
Unnecessary scroll bars in non-EN course catalog

### ISSUE THREAD

**Issue by daynew** [code-dot-org/code-dot-org#39410]
When viewing the /courses page in a non-English language, there are scroll bars in the teal content boxes. There shouldn't be any scrollbars. The box should grow vertically in order to fit the content.
https://studio.code.org/courses/lang/es-mx
![image](https://user-images.githubusercontent.com/1372238/110403135-7c9a9800-8074-11eb-887f-92cf625140e9.png)

**Comment by zxpml** [comment]
I can't test how well this would work in the `/courses` page as I'm not at my PC right now, but `display: table` and `display: table-row` is probably the best solution. According to [caniuse.com](https://caniuse.com/css-table) the only browser that doesn't support `display: table-*` is IE 6 and IE 7, but these browsers probably couldn't support Code.org anyway. When I get to my PC I'll test how well setting content containers to be tables is for content that overflows and needs to be expanded.
