### ISSUE TITLE
properties_encryption_key

### ISSUE THREAD

**Issue by shqlzx** [code-dot-org/code-dot-org#39669]
my local.yml 

properties_encryption_key: 'significantly-sl'
========================
when in run  bundle exec rake install:dashboard --trace
go error:
ArgumentError: key must be 16 bytes
[CDO]/dashboard/lib/encryption.rb:29:in `key='
[CDO]/dashboard/lib/encryption.rb:29:in `decrypt_string'
[CDO]/dashboard/lib/encryption.rb:37:in `decrypt_object'
[CDO]/dashboard/app/dsl/base_dsl.rb:14:in `encrypted'

**Comment by RYG81** [comment]
same here.
any solution?
![image](https://user-images.githubusercontent.com/10570236/124799320-0d757780-df72-11eb-8a24-623318b3c7b8.png)
