### ISSUE TITLE
Got few questions, if some one can guide.

### ISSUE THREAD

**Issue by RYG81** [code-dot-org/code-dot-org#41459]
Hi,

I am researching for my company where we want to have our own coding platform for kids. 
So just wanted to know,
If we can put code-dot-org to my company website domain? 
Can we redesign it to our need? What is allowed and what is not allowed?
Can we set up AppLab and Gamelab separately?
Can we use it for commercial purpose?

Thanks in advance.
RYG81

**Comment by fontie715** [comment]
Hi! Please send an email to support@code.org for this type of request. Thanks!

**Comment by RYG81** [comment]
thanks.
