### ISSUE TITLE
WARNING: level 'CSP U8L3 SFLP 20-21' not seeded properly due to missing CDO.properties_encryption_key

### ISSUE THREAD

**Issue by DanqingLuan** [code-dot-org/code-dot-org#43597]
what is CDO.properties_encryption_key?

**Comment by Erin007** [comment]
Thank you for reaching out. Our Engineering team is busy preparing for the upcoming [Hour of Code](https://hourofcode.com/us) and does not currently have capacity to actively address Github Issues and support contributors at this time. If you have general feedback or questions about the site, please contact our [Customer Support team](https://support.code.org/hc/en-us/requests/new).
