### ISSUE TITLE
Figure out Rate Limiting for Datasets on MySQL

### ISSUE THREAD

**Issue by snickell** [code-dot-org/code-dot-org#55481]
### Rate Limiting

In Firebase we maintain a rate limit per project/channel, 300 writes per 15 seconds, 600 writes per 60 seconds.

1. Where does this data rate come from? Its pretty high. Is this required by the microbit projects?
2. On MySQL we see inserts taking 0.15s per, which if we're not inserting in parallel gives us an insert rate of about 6 inserts/s, which is 90 writes per 15 seconds or 360 per 60 seconds. This is less than our existing limits.
3. Should we be batching these together?

```
{
  "counters": {
    "limits": {
      "15": {
        "lastResetTime": 1654619184297,
        "writeCount": 175
      },
      "60": {
        "lastResetTime": 1654524726608,
        "writeCount": 188
      }
    }
  },
  "serverTime": 1661532798036,
```

**Comment by snickell** [comment]
We're using encrypted cookies for sessions storage, so it should be fast/performant to keep rate counters per-user if that's the approach we want to follow.

**Comment by cnbrenci** [comment]
Firebase is doing async calls and using a websocket to be able to achieve the throughput. It doesn't have to do a roundtrip per transaction. We're investigating how we would deal with auto incrementing the record_id part of the composite primary key without  locking the entire table. Here's a working guess on a query to use:


 ```sql
BEGIN;
  SELECT @id := IFNULL(MAX(record_id),0) + 1 FROM unfirebase.records WHERE channel_id='shared' AND table_name='words' FOR UPDATE;
  INSERT INTO unfirebase.records
     VALUES
     ('shared', 'words', @id, '{}');
  COMMIT;
  
  SELECT * FROM unfirebase.records WHERE channel_id='shared' AND table_name='words' and record_id > 4983;
```
todo: update the quary when we figure out a better one

```sql
# set profiling=1;
BEGIN;
  SELECT MAX(record_id) FROM unfirebase.records WHERE channel_id='shared' AND table_name='Rabbits' FOR UPDATE;
  SELECT @id := IFNULL(MAX(record_id),0)+1 FROM unfirebase.records WHERE channel_id='shared' AND table_name='Rabbits';
  DO SLEEP(10);
  INSERT INTO unfirebase.records
     VALUES
     ('shared', 'Rabbits', @id, '{}');
COMMIT;
  
# show profiles;

# SELECT * FROM unfirebase.records WHERE channel_id='shared' AND table_name='Rabbits';
```

**Comment by snickell** [comment]
See: https://github.com/code-dot-org/code-dot-org/issues/55554#issuecomment-1875967442 for followup to the above (implementing manual auto increment)

**Comment by snickell** [comment]
Profiles look pretty good, on a ProjectDB table with 5000 rows (shared/words), we see overall durations of about a millisecond for the combined set of steps to lock and insert a row (duration column is in seconds).

```
# Query_ID, Duration, Query
'47', '0.00013625', 'BEGIN'
'48', '0.00029125', 'SELECT MIN(record_id) FROM unfirebase.records WHERE channel_id=\'shared\' AND table_name=\'words\' LIMIT 1 FOR UPDATE'
'49', '0.00027725', 'SELECT @id := IFNULL(MAX(record_id),0)+1 FROM unfirebase.records WHERE channel_id=\'shared\' AND table_name=\'words\'\nLIMIT 0, 2000'
'50', '20.00030250', 'DO SLEEP(20)'
'51', '0.00039750', 'INSERT INTO unfirebase.records\n     VALUES\n     (\'shared\', \'words\', @id, \'{}\')'
'52', '0.00017625', 'COMMIT'
```

Additionally we used `SHOW ENGINE INNODB STATUS` to look at the locks being created. Using MIN allows us to have only one lock. We were able to verify when a lock wasn't cleaned up, it only affected the one ProjectDB table, the other rows were accessible.

**Comment by cnbrenci** [comment]
Current impl is client side rate limiting

Want to rate limit on blocks only (not in the UI)
commands.js seems like the right place to put the rate limiting.
Data blocks are re-implemented in multiple commands.js files for Applab and Gamelab. The impls are slightly different. The right way (we think) would prob be to refactor the blocks into a shared spot to be used for the 2 different labs, but that can be broken into a different task/PR.
