### ISSUE TITLE
Optimize getColumn

### ISSUE THREAD

**Issue by snickell** [code-dot-org/code-dot-org#56280]
As per @cnbrenci , curriculum apparently uses the getColumn() block instead of readRecords(). Right now getColumn() is implemented by doing a full table fetch, and extracting the columns on the JS. This is slow, and results in a LOT of extra traffic going over the wire.

Instead, for datablock storage, we can optimize this block by creating a backend get_column method.

**Comment by snickell** [comment]
Phase 1: get new `get_column` backend working
1. On a new branch off of `unfirebase`...
3. Implement new method `DatablockStorageTable.getColumn(column_name)` in `datablock_storage_table.rb`. It might use `DatablockStorageTable.read_records.map do |record|`, and should return a list of column_values. Try using `bin/dashboard-console` to interactively excercise your model until it works like you want.
4. Implement `DatablockStorageController.get_column` in `datablock_storage_controller.rb`, which should be a wafer thin wrapper over 2 that does a render json: call.
5. Implement get_column methods in `datablock_storage/index.html.haml` and test them out using https://localhost-studio.code.org:3000/datablock_storage/CHANNEL_ID_HERE/

Phase 2: rewire javascript
1. Implement `datablockStorage.getColumn(tableName, onSuccess, onError)` in `datablockStorage.js`. DatablockStorage.readRecords and async readRecords pair might be a good pattern to follow.
2. Change applab `commands.js`applabCommands.getColumn` to use Applab.storage.getColumn instead of Applab.storage.readRecords: see https://github.com/code-dot-org/code-dot-org/blob/c921f31afae90a4b18a222497a284a71ffaf8b14/apps/src/applab/commands.js/#L1862-L1873
3. Extract `applabCommands.getColumn` and implement in firebaseStorage.getColumn

**Comment by cnbrenci** [comment]
fixed by https://github.com/code-dot-org/code-dot-org/pull/56988
