### ISSUE TITLE
Implement Library Manifest System

### ISSUE THREAD

**Issue by snickell** [code-dot-org/code-dot-org#56472]
This is a significant work-item, we have a dataset browser, that includes categories and lots of nice metadata. Currently that data is stored in Firebase: https://console.firebase.google.com/project/cdo-v3-shared/database/cdo-v3-shared/data/~2Fv3~2Fchannels~2Fshared~2Fmetadata~2Fmanifest

- [x] Design a DB schema for storing this data
- [x] Design backend APIs for fetching/updating the data, including provisions for our cron jobs to update "current tables"
- [ ] Update Levelbuilder (I think?) to use the new APIs for editing/updating the data
- [x] Implement `DatablockStorage.getLibraryManifest()` using new backend

Fixed by: https://github.com/code-dot-org/code-dot-org/pull/56621

**Comment by snickell** [comment]
The format of the data is like:
```
    const EXAMPLE_MANIFEST_FROM_FIREBASE = {
      categories: [
        {
          datasets: [
            '100 Birds of the World',
            'Bee Colonies',
            'Cats',
            'Dogs',
            'Endangered Species of Canada',
            'Palmer Penguins',
          ],
          name: 'Animals',
          published: true,
        },
      ],
      tables: [
        {
          current: false,
          description:
            'Data and images about 100 different species of birds around the world',
          docUrl: 'https://studio.code.org/data_docs/100-birds/',
          name: '100 Birds of the World',
          published: true,
        },
        {
          current: true,
          description:
            'Live weather five-day forecast data for 100 cities. Updates daily with expected weather conditions.',
          docUrl: 'https://studio.code.org/data_docs/daily-weather/',
          lastUpdated: 1707480317000,
          name: 'Daily Weather',
          published: true,
        },
      ],
    };
```

**Comment by cnbrenci** [comment]
We get/set the LibraryManifest as a single JSON blob. Can we store it in SQL in a single json row instead of over-engineering a whole schema for it?

We could look at the ActsAsSingleton Gem

**Comment by snickell** [comment]
We already have todos for "Update Levelbuilder (I think?) to use the new APIs for editing/updating the data" on our project board, so going to scope this down to the existing checkboxes. Fixed by: 
Fixed by: https://github.com/code-dot-org/code-dot-org/pull/56621
