### ISSUE TITLE
`git diff` not showing .haml diffs (for example)

### ISSUE THREAD

**Issue by snickell** [code-dot-org/code-dot-org#56501]
After our LFS migration, #55759, @kelbyhawn is reporting not seeing HAML, CSS & SCSS diffs in GitHub desktop. 
In theory, we have excluded them from LFS using `.gitattributes`.

I was able to repro:
<img width="960" alt="image" src="https://github.com/code-dot-org/code-dot-org/assets/223277/50193e0e-991d-4d43-9182-d826af0022a2">

**UPDATE:**
Curiously, the file is NOT in LFS, it should be a regular git file, and diffing **does** work on GH.com:
<img width="1038" alt="image" src="https://github.com/code-dot-org/code-dot-org/assets/223277/384896e9-7748-4cd8-ad23-aa52e20e54a6">

Is this a GH Desktop bug?

**Comment by snickell** [comment]
Here are all the `.gitattribute` LFS exclusions: https://github.com/code-dot-org/code-dot-org/blob/8c06377291301a991c948f5c764d99974513e080/.gitattributes/#L16-L40

Focusing on just **haml in sites.v3** for now:
```
pegasus/sites.v3/**/*.haml !text -filter -merge -diff
```

**Comment by snickell** [comment]
For testing GH desktop diffs, I made a test branch where I modified `code-dot-org/pegasus/sites.v3/code.org/public/educate/csa.haml`. Curiously, the file is NOT present in LFS, it should be a normal git file:
<img width="547" alt="image" src="https://github.com/code-dot-org/code-dot-org/assets/223277/15e6ea2e-de59-4971-9cf2-9d5df1913383">

**Comment by snickell** [comment]
Pushing the branch to github.com and opening a test PR, it turns out that GitHub.com IS able to do a visual diff of this file (which it wouldn't for a normal file in LFS, binary or text), so this looks like it might be GitHub Desktop specific?
<img width="1038" alt="image" src="https://github.com/code-dot-org/code-dot-org/assets/223277/384896e9-7748-4cd8-ad23-aa52e20e54a6">

See: https://github.com/code-dot-org/code-dot-org/pull/56502/files

**Comment by bethanyaconnor** [comment]
I'm having a similar problem with the `apps/i18n/common/en_us.json` file, but I don't use Github Desktop. The diff works fine on the Github website, but both in VSCode and in my terminal, I see 
```
diff --git a/apps/i18n/common/en_us.json b/apps/i18n/common/en_us.json
index 82a854286fc..d67ca1aa4c7 100644
Binary files a/apps/i18n/common/en_us.json and b/apps/i18n/common/en_us.json differ
```
when running `git diff`. (For context, the diff I was trying to see is what I ended up committing in 4b5a378be4ce03f4845610f168be33d7aef29347.)

**Comment by snickell** [comment]
@kelbyhawn says she'll be using VSCode's source control feature, which it sounds like does what she needs.

Basic source control diffing (pre-commit) does seem to be working for me on `common/en_us.json`, is there a specific VSCode based invocation not working for you @bethanyaconnor?

<img width="934" alt="image" src="https://github.com/code-dot-org/code-dot-org/assets/223277/6a7cf021-2f8e-4cf2-81c5-dbaf81594aec">

For the command-line, I'm a little confused because en_us.json is not tracked with LFS, and I'd expect the command-line to have the gitattribute config support down cold... would you be up to experiment with: https://github.com/git-lfs/git-lfs/issues/440#issuecomment-501007460 ?

**Comment by bethanyaconnor** [comment]
It's been working on and off in the visual diff VS Code gives me, but that might be an unrelated VS Code issue. It'll miss diffs in large files like `en_us.json` sometimes, especially for big files.

Unfortunately, the command in that comment didn't change anything. :( FWIW, I am also seeing a similar issue with haml files in pegasus with the command line tools.

**Comment by snickell** [comment]
Yup, I can repro thanks @bethanyaconnor . I've retitled the issue, I now believe that `git diff` is having trouble with the "include whole dir, exclude file patterns within that dir" pattern. We know the syntax is working for in-lfs-or-not, but perhaps git diff has a bug, or...? I've created a stackoverflow question related to this: https://stackoverflow.com/questions/77991616/git-diff-not-working-for-files-excluded-from-git-lfs

In the meantime, I'm going to experiment with using different `.gitattributes` lines for doing the exclusions:
```
pegasus/sites.v3/**/*.haml !text -filter -merge -diff
```

**Comment by snickell** [comment]
Related report from @Nokondi :
> Hey all, I'm having an issue with drone. It's not getting past the clone stage. Here's the PR: https://github.com/code-dot-org/code-dot-org/pull/56495 and the error message from drone:
> warning: Cannot merge binary files: apps/i18n/common/en_us.json (HEAD vs. origin/staging)
> Auto-merging apps/i18n/common/en_us.json
> CONFLICT (content): Merge conflict in apps/i18n/common/en_us.json
> Automatic merge failed; fix conflicts and then commit the result.
> (no merge conflicts are showing up in github)

Not supporting text merging is potentially an even bigger problem than diff not working in some tools.

**Comment by snickell** [comment]
I asked a stackoverflow question on this last week but haven't gotten any bites yet: https://stackoverflow.com/questions/77991616/git-diff-not-working-for-files-excluded-from-git-lfs?noredirect=1#comment137496156_77991616

**Comment by snickell** [comment]
It may be that we can workaround the bug in some but not all git ecosystem tools by being more explicit on the merge and diff strategy.

Compare a file having trouble:
```
> git check-attr -a -- pegasus/sites.v3/hourofcode.com/views/front_join_us.haml
pegasus/sites.v3/hourofcode.com/views/front_join_us.haml: diff: unset
pegasus/sites.v3/hourofcode.com/views/front_join_us.haml: merge: unset
pegasus/sites.v3/hourofcode.com/views/front_join_us.haml: filter: unset
```

To a file that's "totally normal":
```
> git check-attr -a -- apps/package.json
# no output
```

It appears that "unset" is not the same thing as "not set" :-P

**Comment by snickell** [comment]
Aha!

With current .gitattributes `apps/i18n/**/en_us.json !text -filter -merge -diff`:
```
> git diff apps/i18n/common/en_us.json
diff --git a/apps/i18n/common/en_us.json b/apps/i18n/common/en_us.json
index f0ff8d1dfd5..f79e33cb032 100644
Binary files a/apps/i18n/common/en_us.json and b/apps/i18n/common/en_us.json differ
```

But if I unspecify the attributes instead of unsetting them `apps/i18n/**/en_us.json !text !filter !merge !diff`:
```
> git diff apps/i18n/common/en_us.json
diff --git a/apps/i18n/common/en_us.json b/apps/i18n/common/en_us.json
index f0ff8d1dfd5..f79e33cb032 100644
--- a/apps/i18n/common/en_us.json
+++ b/apps/i18n/common/en_us.json
@@ -2782,6 +2782,7 @@
   "yourEmailPlaceholder": "you@example.com",
   "yourName": "Your name",
   "yourNameCaps": "Your Name",
+  "boop": "snek",
   "yourResponseSubmitted": "Your response has been submitted!",
   "yourSchoolAdminButton": "View administrator guide",
   "yourSchoolAdminDesc": "View resources on how to get started or expand opportunities",
```

**Comment by snickell** [comment]
I believe I have a fix for this issue in: https://github.com/code-dot-org/code-dot-org/pull/56737

**Comment by snickell** [comment]
PR merged
