### ISSUE TITLE
Investigate Gamelab

### ISSUE THREAD

**Issue by snickell** [code-dot-org/code-dot-org#56565]
commands.js for gamelab uses studioApp() singleton and then accesses `studioApp().storage`. https://github.com/code-dot-org/code-dot-org/blob/4247d207588fb3d21699ce3bbd00bf7feb849baa/apps/src/p5lab/gamelab/commands.js/#L25-L29

How is `storage` set here? We initialize storage in applab.js.... is that setting studioApp().storage too?

Check if gamelab is working with data blocks.

**Comment by cnbrenci** [comment]
Gamelab is not working 

![Image](https://github.com/code-dot-org/code-dot-org/assets/24951544/7f135955-11d9-4ef5-9100-cbc81861375d)
