### ISSUE TITLE
Figure out DCDO flags for "percent_new_applabs_use_datablock_storage"

### ISSUE THREAD

**Issue by snickell** [code-dot-org/code-dot-org#56625]
We now have the ability to mark individual projects as `use_datablock_storage` or not. Now we need a way to modify the percentage of new applab projects that are created with `use_datablock_storage=true`. Initially, we'll set this to a very small value, like 1% of newly applabs will have use_datablock_storage set.

Then, as we gain confidence, we'll increase the number, preferably without having to do a redeploy.

I believe DCDO flags are the right mechanism for this, but I don't know a lot about using them, so we have to investigate this.

**Comment by cnbrenci** [comment]
Relevant docs: 

https://docs.google.com/document/d/1l5ISiVT329Y9uKLZYPmrSvu63O3DrB2iVX4xKsfeQhA/edit#bookmark=id.wjb27476lstm

PR for interface for editing https://github.com/code-dot-org/code-dot-org/pull/56362

**Comment by snickell** [comment]
Fixed by #56699
