### ISSUE TITLE
Prep for bug bash

### ISSUE THREAD

**Issue by cnbrenci** [code-dot-org/code-dot-org#56646]
Things we need to do for the bug bash:

- [x] Be able to set up an adhoc to have 100% new projects use datablock storage (the DCDO piece)
- [x] Set up the bugbash adhoc
- [x] Seed data to the adhoc
- [x] Some indication for people to make sure their project is using the datablock storage
- [x] Document for folks to add bugs (can prob rip off some from blockly bug bash doc) with any caveats and setup instructions
- [x] Does gamelab work? [#56565](https://github.com/code-dot-org/code-dot-org/issues/56565)
- [x] Do our data blocks basically work in applab? Its been a while since we checked....

**Comment by snickell** [comment]
Adhoc setup TODO:
- [x] Verify https://adhoc-unfirebase-studio.cdn-code.org loads
- [x] Expand linux filesystem to 256GB: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/recognize-expanded-volume-linux.html
- [x] Set `dashboard_workers: 32` in globals.yml
- [x] Stop instance and change instance type to `m5.8xlarge`
- [x] Start instance and verify https://adhoc-unfirebase-studio.cdn-code.org loads
- [x] Update adhoc secret https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=CfnStack%2Fadhoc-unfirebase%2Fdb_credential_admin&region=us-east-1
- [x] Update adhoc secret https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=CfnStack%2Fadhoc-unfirebase%2Fdb_endpoint_writer&region=us-east-1
- [x] Update adhoc secret 
- [x] Update locals.yml from previously saved config
- [x] sudo systemctl restart dashboard
- [x] Migration hand-waving here
- [x] Verify https://adhoc-unfirebase-studio.cdn-code.org loads
- [x] Run `DCDO.set('fraction_of_new_projects_use_datablock_storage', 1.0)`

**Comment by snickell** [comment]
![Image](https://github.com/code-dot-org/code-dot-org/assets/223277/d672fdd4-9602-4948-b639-b383f181fcb5)

**Comment by snickell** [comment]
https://adhoc-unfirebase-studio.cdn-code.org/

![Image](https://github.com/code-dot-org/code-dot-org/assets/223277/e37a9c05-4791-4978-8c6d-e20a2e8afe59)
