### ISSUE TITLE
After importing a table with booleans, clicking "Convert to boolean" doesn't convert the stringified values to booleans. Clicking "convert to number" replaces all values with 0.

### ISSUE THREAD

**Issue by sanchitmalhotra126** [code-dot-org/code-dot-org#56757]
Project link: https://adhoc-unfirebase-studio.cdn-code.org/projects/applab/VIqGE1kRtmBw2ZBb1L9J5wKrr4dA9uJiChJck9lLxhM/edit/ (see "My Table - imported")

Edit: this does not repro with Firebase

**Comment by snickell** [comment]
Hey @sanchitmalhotra126 , I wasn't able to immediately repro, and unfortunately the share link apparently doesn't include the dataset. Any chance you could export the table in question?

**Comment by cnbrenci** [comment]
@sanchitmalhotra126 I was able to repro! 

NoMethodError in DatablockStorageController#coerce_column

undefined method `to_b' for "true":String
Did you mean?  to_d
               to_r
               to_f
               to_i
               to_s
               to_c
Extracted source (around line #191):

#189       value.to_f
#190     when 'boolean'
*191       value.to_b
#192     end
#193   end
#194 

Extracted source (around line #204):

#202     records.each do |record|
#203       # column type is one of: string, number, boolean, date
*204       record.record_json[column_name] = _coerce_type(record.record_json[column_name], column_type)
#205     end
#206   end
#207

**Comment by cnbrenci** [comment]
For the numbers changing to 0, looks like the same behavior in firebase projects. "true" and "false" convert to 0, "1" and "2" convert to 1 and 2.

**Comment by cnbrenci** [comment]
boolean coercion fixed with https://github.com/code-dot-org/code-dot-org/pull/56279/commits/392447827e4f9987d638cf4b54b8f984cd53c01b

**Comment by snickell** [comment]
Confirmed fix on https://adhoc-unfirebase-studio.cdn-code.org/projects/applab/ovdkvdEWX1gMg1owzPq4sXbzjEv7G6SoUFGErQ3CUWk/edit, working for number to boolean coercion, and for "true" and "false"
