### ISSUE TITLE
Export CSV not implemented

### ISSUE THREAD

**Issue by snickell** [code-dot-org/code-dot-org#56996]
We should move export CSV from being a middleware to being a method on datablock_storage_controller.rb, but it should work for both Firebase and DatablockStorage.

**Comment by snickell** [comment]
When we migrate CSV export to the DatablockStorageController, do we want to completely delete `dashboard/legacy/middleware/tables_api.rb`? It looks like @davidsbailey already gutted most of the `tables_api.rb` in a previous refactor, and this might be the only method left. Thought Dave might have a sense if its safe to delete once we delete `get %r{/v3/export-firebase-tables/([^/]+)/([^/]+)$}` or if there's another justification/side-effect for this file to exist.

**Comment by davidsbailey** [comment]
dashboard/legacy is all legacy code which does not fit well into rails. If you're rewriting this functionality, better to do so outside of dashboard/legacy and remove tables_api.rb.

**Comment by snickell** [comment]
Fixed by PR: #57134

We're still using the tables_api.rb code in the Firebase code path while we have both versions deployed during migration. I marked tables_api.rb as "to remove post-firebase-cleanup": #56994
