### ISSUE TITLE
Delete datablock storage data on account deletion

### ISSUE THREAD

**Issue by snickell** [code-dot-org/code-dot-org#57004]
Probably we just need a line in delete_accounts_helper.rb to manage this.

See:
- **`delete_accounts_helper.rb`:** https://github.com/code-dot-org/code-dot-org/blob/2a02fd1aefe55f98eb454876def9713e716de5da/lib/cdo/delete_accounts_helper.rb/#L73-L77
- Test: `datasets_controller_test.rb`: https://github.com/code-dot-org/code-dot-org/blob/2a02fd1aefe55f98eb454876def9713e716de5da/dashboard/test/controllers/datasets_controller_test.rb/#L34-L36
- Test: `delete_accounts_helper_test.rb`: https://github.com/code-dot-org/code-dot-org/blob/2a02fd1aefe55f98eb454876def9713e716de5da/dashboard/test/helpers/delete_accounts_helper_test.rb/#L53-L56

**Comment by cnbrenci** [comment]
This one unrelated? Test: datasets_controller_test.rb: https://github.com/code-dot-org/code-dot-org/blob/2a02fd1aefe55f98eb454876def9713e716de5da/dashboard/test/controllers/datasets_controller_test.rb/#L34-L36

**Comment by snickell** [comment]
We had to revert due to breaking other drone tests: https://github.com/code-dot-org/code-dot-org/pull/59692

**Comment by snickell** [comment]
Did we re-merge this already? I'm re-opening to be cautious but we might have refixed this already.

**Comment by snickell** [comment]
Fixed by https://github.com/code-dot-org/code-dot-org/pull/59695
