### ISSUE TITLE
Fix datablock_storage debug view in prod

### ISSUE THREAD

**Issue by cnbrenci** [code-dot-org/code-dot-org#57628]
https://app.honeybadger.io/projects/3240/faults/105874866/01HSHNQ2ZVJHQNEGWRQF8KS9TN?q=occurred.after%3A%221+hours+ago%22

![Image](https://github.com/code-dot-org/code-dot-org/assets/24951544/f6ec49c7-9d67-494e-9fbc-b9fcb94a9d87)

**Comment by snickell** [comment]
This is showing up in honeybadger: https://app.honeybadger.io/projects/3240/faults?q=request.url%3A%22%2Adatablock%2A%22+-is%3Aresolved+-is%3Aignored#:~:text=NoMethodError%20in%20datablock_storage%23index

We should resolve the honeybadger issue when we merge this.

**Comment by snickell** [comment]
Fixed by https://github.com/code-dot-org/code-dot-org/pull/57630
