### ISSUE TITLE
CSV import parsing failures don't show a user facing error

### ISSUE THREAD

**Issue by cnbrenci** [code-dot-org/code-dot-org#58614]

**Comment by cnbrenci** [comment]
Follow-up from [#57676](https://github.com/code-dot-org/code-dot-org/issues/57676)

**Comment by snickell** [comment]
We should notify customer support when we fix this, since its apparently an issue that's getting reported. We need investigation first to figure out if Firebase throws an error in this condition or what.

**Comment by cnbrenci** [comment]
https://codedotorg.slack.com/archives/C03DBDN67B7/p1716358239957609?thread_ts=1716206889.397779&cid=C03DBDN67B7

cx notified! closing!
