### ISSUE TITLE
UI tests for data blocks and data tabs

### ISSUE THREAD

**Issue by cnbrenci** [code-dot-org/code-dot-org#58950]
The ec_data_blocks tests are proving to be difficult to mock and what we really want is end-to-end tests instead.

There are eyes tests for data blocks already (but they are missing getColumn so as long as we add that we should be able to remove the ec_data_blocks tests for that block without reducing coverage)

https://github.com/code-dot-org/code-dot-org/blob/f35aff5378a59c3c66603184a475664a0208c22c/dashboard/test/ui/features/star_labs/applab/data_blocks.feature/#L3-L14

We want to modify allthethings and add to these tests

**Comment by snickell** [comment]
1. Modify http://studio.code.org/s/allthethings/lessons/18/levels/8?noautoplay=true (using local levelbuilder mode?) to include better test coverage
2. Get this passing: `bundle exec rake test:ui feature=./dashboard/test/ui/features/star_labs/applab/data_blocks.feature`

**Comment by snickell** [comment]
Fixed by #59667
