### ISSUE TITLE
Signed out users can't access datablock storage on projects they don't own

### ISSUE THREAD

**Issue by cnbrenci** [code-dot-org/code-dot-org#59339]
see slack https://codedotorg.slack.com/archives/C05DMS18MEX/p1718997900072409

**Comment by cnbrenci** [comment]
Noting zendesk tickets that have come in reporting this bug:

https://codeorg.zendesk.com/agent/tickets/499720
https://codeorg.zendesk.com/agent/tickets/500598
https://codeorg.zendesk.com/agent/tickets/501112

**Comment by snickell** [comment]
It looks like all we'd have to do is remove this line from datablock_storage_controller.rb:
```
  before_action :authenticate_user!
```
