### ISSUE TITLE
Remove firebase secrets from AWS secrets manager

### ISSUE THREAD

**Issue by snickell** [code-dot-org/code-dot-org#59831]
Removed the following from `config.yml.erb` in #59824 :
```
firebase_secret: !Secret
firebase_shared_secret: !Secret
```

Should remove the corresponding keys from AWS secrets manager in all environments.

**Comment by snickell** [comment]
After removing the AWS keys, should also probably remove a reference in `iam.yml.erb` for the `ContributorSecretsPolicy` granting access to: [development/cdo/firebase_secret-ngO5yy](https://github.com/code-dot-org/code-dot-org/blob/0e158e16293d1fbbafa8a29ae02f6356a8defd97/aws/cloudformation/iam.yml.erb/#L661-L662)

**Comment by snickell** [comment]
@code-dot-org/infrastructure We're not quite ready to do this , but how do we remove secrets from the AWS secrets manager. Just manually remove them? Are they managed by anything?

I'd like to wait for the [Final Removal of all traces of Firebase PR](https://github.com/code-dot-org/code-dot-org/pull/59824) to merge first, and give it a few days to settle, but we'll be ready to drop the secrets pretty soon.

Related issues to remove firebase secrets from:
- GitHub Actions: #59832 
- Drone: #59830
- Any other places ya'll can think of?

Also, very happy with this and thought you might appreciate it too:
![Image](https://github.com/user-attachments/assets/af6bb9ca-d68f-47e0-8a42-aa7e790ecba9)

**Comment by cat5inthecradle** [comment]
Once you've removed references from the codebase, they can be manually deleted from AWS.

**Comment by cnbrenci** [comment]
Once this is done, ping Suresh to clean up his backups of the secrets - see https://codedotorg.slack.com/archives/C0T0PNTM3/p1721671757308039?thread_ts=1721668691.529179&cid=C0T0PNTM3

**Comment by snickell** [comment]
We're removing:
```
adhoc/cdo/firebase_shared_secret | - | July 22, 2024
-- | -- | --
development/cdo/firebase_secret | - | July 17, 2024
development/cdo/firebase_shared_secret | - | July 17, 2024
production/cdo/firebase_shared_secret | - | July 22, 2024
levelbuilder/cdo/firebase_shared_secret | - | July 17, 2024
test/cdo/firebase_shared_secret | - | July 18, 2024
staging/cdo/firebase_shared_secret | - | July 19, 2024
adhoc/cdo/firebase_secret | - | July 22, 2024
production/cdo/firebase_secret | - | November 2, 2023
levelbuilder/cdo/firebase_secret | - | July 17, 2024
test/cdo/firebase_secret | - | July 18, 2024
staging/cdo/firebase_secret

[adhoc/cdo/firebase_shared_secret](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=adhoc%2Fcdo%2Ffirebase_shared_secret&region=us-east-1)
-
July 22, 2024
[development/cdo/firebase_secret](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=development%2Fcdo%2Ffirebase_secret&region=us-east-1)
-
July 17, 2024
[development/cdo/firebase_shared_secret](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=development%2Fcdo%2Ffirebase_shared_secret&region=us-east-1)
-
July 17, 2024
[production/cdo/firebase_shared_secret](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=production%2Fcdo%2Ffirebase_shared_secret&region=us-east-1)
-
July 22, 2024
[levelbuilder/cdo/firebase_shared_secret](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=levelbuilder%2Fcdo%2Ffirebase_shared_secret&region=us-east-1)
-
July 17, 2024
[test/cdo/firebase_shared_secret](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=test%2Fcdo%2Ffirebase_shared_secret&region=us-east-1)
-
July 18, 2024
[staging/cdo/firebase_shared_secret](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=staging%2Fcdo%2Ffirebase_shared_secret&region=us-east-1)
-
July 19, 2024
[adhoc/cdo/firebase_secret](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=adhoc%2Fcdo%2Ffirebase_secret&region=us-east-1)
-
July 22, 2024
[production/cdo/firebase_secret](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=production%2Fcdo%2Ffirebase_secret&region=us-east-1)
-
November 2, 2023
[levelbuilder/cdo/firebase_secret](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=levelbuilder%2Fcdo%2Ffirebase_secret&region=us-east-1)
-
July 17, 2024
[test/cdo/firebase_secret](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=test%2Fcdo%2Ffirebase_secret&region=us-east-1)
-
July 18, 2024
[staging/cdo/firebase_secret](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=staging%2Fcdo%2Ffirebase_secret&region=us-east-1)
```

**Comment by snickell** [comment]
We removed these secrets (marked as remove in 30 days):

- adhoc/cdo/firebase_shared_secret
- development/cdo/firebase_secret
- development/cdo/firebase_shared_secret
- staging/cdo/firebase_shared_secret
- adhoc/cdo/firebase_secret
- staging/cdo/firebase_secret

I did not have permissions to delete the following keys, @code-dot-org/infrastructure  could you delete these for us:

- [x] production/cdo/firebase_shared_secret
- [x] levelbuilder/cdo/firebase_shared_secret
- [x] test/cdo/firebase_shared_secret
- [x] production/cdo/firebase_secret
- [x] levelbuilder/cdo/firebase_secret
- [x] test/cdo/firebase_secret
